export type Lesson = { title: string; beginner: string; advanced: string; control: string; unit: string; initial: number; question: string; options: string[]; correct: number; explanation: string };
export const lessons: Record<string, Lesson> = {
  imbalance: { title: 'Accuracy can hide a class', beginner: 'A model can score well by always choosing the most common class, while never recognizing the smaller class.', advanced: 'For a binary majority-only classifier, accuracy equals majority prevalence and balanced accuracy is 0.5 while both classes are present. Inspect per-class recall and macro metrics.', control: 'Majority-class share', unit: '%', initial: 80, question: 'A majority-only classifier gets 90% accuracy. What should you inspect next?', options: ['Per-class recall and a majority baseline', 'Only the overall accuracy', 'The number of training epochs alone'], correct: 0, explanation: 'Overall accuracy can conceal zero minority recall. Per-class metrics reveal who the model fails.' },
  shift: { title: 'The environment changes the score', beginner: 'Even if a model behaves the same within each group, its overall accuracy changes when the mixture of easy and hard examples changes.', advanced: 'This toy mixture fixes group accuracies at 95% and 55%. Aggregate accuracy is (1-p)*0.95 + p*0.55. A changed aggregate does not identify whether covariates, labels, or conditional relationships changed.', control: 'Hard examples in evaluation', unit: '%', initial: 50, question: 'Does a production accuracy drop alone prove distribution shift?', options: ['Yes, every drop proves shift', 'No; compare data, preprocessing, and evaluation', 'No; production accuracy is never useful'], correct: 1, explanation: 'The gap is a signal. Changes in preprocessing, labeling, and evaluation can also explain it.' },
  leakage: { title: 'When evaluation has seen the answers', beginner: 'Leaked information can make evaluation look easier than deployment. Repeated rows deserve an audit, but can also represent legitimate repeated observations.', advanced: 'The demonstration assumes 100% accuracy on leaked examples and 60% on independent examples. Observed accuracy rises with leakage fraction; this is an illustration, not an estimate of your experiment.', control: 'Assumed leaked evaluation examples', unit: '%', initial: 30, question: 'What is a useful leakage verification experiment?', options: ['Trust the highest validation score', 'Put more duplicates in validation', 'Audit provenance and re-split by entity'], correct: 2, explanation: 'Provenance and entity-aware splitting test whether evaluation contains information unavailable at prediction time.' },
  missing: { title: 'Missing data changes what the model sees', beginner: 'Removing every incomplete row can discard much more data than expected. The missingness mechanism matters as much as its frequency.', advanced: 'With five features independently missing at rate p, complete-row probability is (1-p)^5. Correlated missingness changes this relationship. Fit imputation on training data only.', control: 'Missingness per feature', unit: '%', initial: 10, question: 'Where should an imputer be fitted?', options: ['Training data only, then applied to held-out splits', 'All splits together', 'The test split first'], correct: 0, explanation: 'Fitting preprocessing on held-out data can introduce leakage into evaluation.' },
  'possible-overfitting': { title: 'Learning the training set too closely', beginner: 'Training loss can keep falling while performance on unseen data worsens. More training is not always better.', advanced: 'The toy curves separate optimization on the training sample from held-out generalization. Validation-based early stopping selects a checkpoint; a separate untouched test set is still needed.', control: 'Training epoch', unit: '', initial: 30, question: 'Which pattern suggests overfitting?', options: ['Both losses consistently fall', 'Training loss falls while validation loss rises', 'A single low training loss proves it'], correct: 1, explanation: 'Diverging loss trends motivate an overfitting hypothesis, assuming comparable loss definitions and stable splits.' },
  'possible-stalled-learning': { title: 'A plateau has more than one explanation', beginner: 'A flat loss can mean that learning has stalled, or that the model has already converged. Check whether parameters and gradients are changing.', advanced: 'For L(w)=w^2/2, gradient descent gives w_next=(1-eta)*w. Very small eta yields slow progress. A plateau alone cannot distinguish optimization trouble from convergence.', control: 'Learning-rate dial (eta = dial / 100)', unit: '', initial: 5, question: 'What does a flat loss curve establish?', options: ['The model is certainly broken', 'The dataset must have leakage', 'More checks are needed to distinguish convergence from a problem'], correct: 2, explanation: 'Check updates, gradients, and small-batch fitting before concluding that a plateau is a failure.' },
  'possible-unstable-training': { title: 'Updates can overshoot', beginner: 'Large updates may jump past a good solution. But noisy batches and changing evaluation conditions can also make a curve oscillate.', advanced: 'For the toy quadratic L(w)=w^2/2, eta above 1 alternates the sign of w; eta above 2 makes its magnitude grow. This threshold is specific to this quadratic, not a universal learning-rate rule.', control: 'Learning-rate dial (eta = dial / 40)', unit: '', initial: 90, question: 'What is a controlled first check for oscillating loss?', options: ['Change the data, optimizer, and batch size together', 'Compare a lower learning rate with other conditions fixed', 'Assume every oscillation is overfitting'], correct: 1, explanation: 'Changing one factor and holding the others fixed makes the result interpretable.' },
};
export function demonstration(id: string, dial: number): { label: string; value: number; suffix: string; note: string } {
  const n=Math.min(100,Math.max(0,dial));
  if(id==='imbalance') return {label:'Majority-only accuracy',value:Math.max(50,n),suffix:'%',note:'Minority recall stays 0% for shares below 100%. At 100%, minority recall is undefined because that class is absent.'};
  if(id==='shift') return {label:'Mixture accuracy',value:95-.4*n,suffix:'%',note:'Assumes fixed accuracies: 95% on easy examples, 55% on hard examples.'};
  if(id==='leakage') return {label:'Apparent evaluation accuracy',value:60+.4*n,suffix:'%',note:'Assumes perfect prediction on leaked examples and 60% on independent examples.'};
  if(id==='missing') return {label:'Expected complete rows (out of 1,000)',value:1000*(1-n/100)**5,suffix:'',note:'Assumes five features with independent missingness. Real missingness may be correlated.'};
  if(id==='possible-overfitting') return {label:'Illustrative validation loss',value:.2+(n-35)**2/10000,suffix:'',note:`Toy training loss: ${(1/(1+n/10)).toFixed(3)}. Toy validation loss is lowest at epoch 35; these are not fitted to your metrics.`};
  const eta=id==='possible-unstable-training'?n/40:n/100;
  return {label:'Toy loss after 10 updates',value:.5*(1-eta)**20,suffix:'',note:`Starting w=1; L(w)=w squared / 2; learning rate ${eta.toFixed(2)}. Weight after one update: ${(1-eta).toFixed(2)}. This model illustrates update size, not a recommended learning rate.`};
}
