"use client";
import { createContext, useCallback, useContext, useEffect, useState, type Dispatch, type ReactNode, type SetStateAction } from 'react';
import { diagnose } from '../lib/dataset';
import { caseMarkdown, emptySnapshot, parseCase, STORAGE_KEY, type SavedCase, type Snapshot } from '../lib/cases';
type CaseContextValue={snapshot:Snapshot;update:<K extends keyof Snapshot>(key:K,value:SetStateAction<Snapshot[K]>)=>void;newCase:()=>void};
const CaseContext=createContext<CaseContextValue|null>(null);
export function useCaseState<K extends keyof Snapshot>(key:K):[Snapshot[K],Dispatch<SetStateAction<Snapshot[K]>>] {
 const context=useContext(CaseContext);if(!context)throw new Error('Case provider required.');
 const update=context.update;
 const setter=useCallback((value:SetStateAction<Snapshot[K]>)=>update(key,value),[key,update]);
 return [context.snapshot[key],setter];
}
export function useNewCase(){const context=useContext(CaseContext);if(!context)throw new Error('Case provider required.');return context.newCase;}
function download(name:string,text:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function CaseManager({children}:{children:ReactNode}) {
 const [snapshot,setSnapshot]=useState<Snapshot>(emptySnapshot),[cases,setCases]=useState<SavedCase[]>([]),[name,setName]=useState('Untitled investigation'),[notes,setNotes]=useState(''),[active,setActive]=useState(''),[revision,setRevision]=useState(0),[message,setMessage]=useState(''),[ready,setReady]=useState(false),[dirty,setDirty]=useState(false),[storageBlocked,setStorageBlocked]=useState(false),[importing,setImporting]=useState(false);
 useEffect(()=>{let alive=true;Promise.resolve().then(()=>{if(!alive)return;try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const list:unknown=JSON.parse(raw);if(!Array.isArray(list))throw new Error('Invalid case library');setCases(list.map(item=>parseCase(JSON.stringify(item))));}}catch{setStorageBlocked(true);setMessage('Saved cases could not be read. Existing browser data was left unchanged; export your current work before troubleshooting.');}setReady(true);});return()=>{alive=false;};},[]);
 useEffect(()=>{if(!dirty)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const update=useCallback(<K extends keyof Snapshot>(key:K,value:SetStateAction<Snapshot[K]>)=>{setSnapshot(previous=>{const nextValue=typeof value==='function'?(value as (old:Snapshot[K])=>Snapshot[K])(previous[key]):value;const next={...previous,[key]:nextValue};if(['evidence','datasets','target','task'].includes(key)&&nextValue!==previous[key]){next.experiments={};next.answers={};}return next;});setDirty(true);},[]);
 function persist(next:SavedCase[]){if(storageBlocked){setMessage('The existing case library is unreadable. Export JSON to keep your work; it will not be overwritten.');return false;}try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next));setCases(next);return true;}catch{setMessage('Browser storage is unavailable or full. Your workspace is intact; export JSON to keep a copy.');return false;}}
 function current():SavedCase{return {version:1,id:active||crypto.randomUUID(),name:name.trim()||'Untitled investigation',notes,updatedAt:new Date().toISOString(),snapshot:{...snapshot,complete:Boolean(snapshot.evidence)}};}
 function save(){const record=current();try{parseCase(JSON.stringify(record));}catch{setMessage('Finish the current analysis before saving, or reduce the case size.');return;}if(persist([record,...cases.filter(c=>c.id!==record.id)])){setActive(record.id);setName(record.name);setDirty(false);setMessage('Case saved in this browser.');}}
 function canLeave(){return !dirty||window.confirm('Discard unsaved workspace changes? Save or export first to keep them.');}
 function newCase(){if(!canLeave())return;setSnapshot(emptySnapshot());setName('Untitled investigation');setNotes('');setActive('');setDirty(false);setRevision(r=>r+1);setMessage('New investigation.');}
 function open(record:SavedCase){if(!canLeave())return;setSnapshot(record.snapshot);setName(record.name);setNotes(record.notes);setActive(record.id);setDirty(false);setRevision(r=>r+1);setMessage('Case opened. Parsed evidence and dataset rows restored; original file-picker selections are not stored.');}
 async function importFile(file?:File){if(!file)return;setImporting(true);try{if(file.size>8_000_000)throw new Error('Case exceeds the 8 MB import limit.');const record=parseCase(await file.text());record.id=crypto.randomUUID();if(persist([record,...cases]))setMessage('Imported as a new saved case. Choose Open to load it.');}catch(error){setMessage(error instanceof Error?error.message:'Could not import case.');}finally{setImporting(false);}}
  return <CaseContext.Provider value={{snapshot,update,newCase}}><a className="skip-link" href="#workspace">Skip to investigation</a><section className="case-manager" aria-labelledby="case-manager-heading"><details><summary id="case-manager-heading">01 / Investigation library <span>{dirty?'Unsaved changes':active?'Saved case open':'Local browser storage'}</span></summary><p className="description">Save explicitly to keep parsed evidence, datasets, notes, context answers, and recorded experiments after reload. JSON exports include these data. Browser storage is local to this browser and site.</p><div className="experiment-fields"><label>Case name<input maxLength={120} value={name} onChange={e=>{setName(e.target.value);setDirty(true);}}/></label><label>Investigation notes<textarea value={notes} onChange={e=>{setNotes(e.target.value);setDirty(true);}}/></label></div><fieldset disabled={importing} className="case-actions"><button disabled={!ready} onClick={save}>Save case</button><button onClick={newCase}>New case</button><button onClick={()=>download('whylab-case.json',JSON.stringify(current(),null,2),'application/json')}>Export JSON</button><button onClick={()=>download('whylab-report.md',caseMarkdown(current(),diagnose(snapshot.evidence,snapshot.datasets,snapshot.target,snapshot.task,snapshot.answers)),'text/markdown')}>Export Markdown</button><label>Import JSON<input type="file" accept=".json" disabled={!ready} onChange={e=>{void importFile(e.target.files?.[0]);e.target.value='';}}/></label></fieldset><ul className="case-list">{cases.map(c=><li key={c.id}><span>{c.name}<small>{new Date(c.updatedAt).toLocaleString()}</small></span><button disabled={importing} onClick={()=>open(c)}>Open</button><button disabled={importing} onClick={()=>{const renamed=window.prompt('New case name',c.name);if(!renamed?.trim())return;if(renamed.trim().length>120){setMessage('Use a name of at most 120 characters.');return;}if(persist(cases.map(item=>item.id===c.id?{...item,name:renamed.trim()}:item))&&active===c.id)setName(renamed.trim());}}>Rename</button><button disabled={importing} onClick={()=>{if(window.confirm(`Delete saved case "${c.name}"?`)&&persist(cases.filter(item=>item.id!==c.id))){if(active===c.id){setActive('');setDirty(true);}setMessage('Saved case deleted. The current workspace was kept.');}}}>Delete</button></li>)}</ul>{ready&&!cases.length&&<p className="description">No saved cases yet.</p>}<p role="status" className="description">{message}</p></details></section><div key={revision}>{children}</div></CaseContext.Provider>;
}
