"use client";
import { useEffect, useRef, useState } from 'react';
import { metricColumns, type Evidence } from '../lib/evidence';
import { runIngestion, type InputFile } from '../lib/ingestion-client';
import { useCaseState } from './case-manager';
export default function EvidenceImport({disabled,onBusyChange}:{disabled:boolean;onBusyChange:(busy:boolean)=>void}) {
  const [,setEvidence]=useCaseState('evidence'),[,setComplete]=useCaseState('complete');
  const [files,setFiles]=useState<InputFile[]>([]),[headers,setHeaders]=useState<{name:string;headers:string[]}[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const controller=useRef<AbortController|null>(null);
  useEffect(()=>()=>controller.current?.abort(),[]);
  useEffect(()=>{onBusyChange(busy);return()=>onBusyChange(false);},[busy,onBusyChange]);
  async function choose(selected:FileList|null){if(!selected)return;controller.current?.abort();const next=new AbortController();controller.current=next;setBusy(true);setError('');setNotice('');setFiles([]);setHeaders([]);try{const list=Array.from(selected);if(list.length>5||list.reduce((n,f)=>n+f.size,0)>10_000_000)throw new Error('Select up to five files, at most 10 MB combined.');if(list.some(f=>! /\.(csv|json|log|txt)$/i.test(f.name)))throw new Error('Choose CSV, JSON, LOG, or TXT files.');if(new Set(list.map(f=>f.name)).size!==list.length)throw new Error('Use distinct file names so evidence can be traced to its source.');const loaded=await Promise.all(list.map(async f=>({name:f.name,text:await f.text()})));if(next.signal.aborted)return;const preview=await runIngestion<{name:string;headers:string[]}[]>('preview',loaded,next.signal);if(preview.some(p=>p.headers.length>100))throw new Error('Use at most 100 columns per CSV for interactive mapping.');setFiles(loaded);setHeaders(preview);}catch(e){if(!next.signal.aborted)setError(e instanceof Error?e.message:'Could not read files.');}finally{if(!next.signal.aborted)setBusy(false);}}
  async function analyze(){controller.current?.abort();const next=new AbortController();controller.current=next;setBusy(true);setError('');setNotice('');try{const evidence=await runIngestion<Evidence>('analyze',files,next.signal);setEvidence(evidence);setComplete(true);setNotice('Evidence loaded into the investigation results above. Save the case to retain the parsed results.');}catch(e){if(!next.signal.aborted)setError(e instanceof Error?e.message:'Parsing failed.');}finally{if(!next.signal.aborted)setBusy(false);}}
  return <section className="panel dataset-lab" aria-labelledby="import-heading"><span className="eyebrow cyan">07 / EXTENDED EVIDENCE IMPORT</span><h2 id="import-heading">Bring the whole experiment.</h2><p className="description">Select up to five related files (10 MB total). Map unfamiliar CSV headers to metric names. Files are analyzed independently; the first available epoch history supplies the chart. Parsed results replace the current investigation and invalidate its verification history.</p><label className="extended-file">Evidence files<input type="file" multiple accept=".csv,.json,.log,.txt" disabled={busy||disabled} onChange={e=>{void choose(e.target.files);e.target.value='';}}/></label>
    {headers.map((file,i)=><details key={file.name} className="mapping-file"><summary>{file.name}{file.headers.length?` / ${file.headers.length} columns`:' / automatic log or JSON parsing'}</summary>{file.headers.length>0&&<div className="mapping-grid">{file.headers.map(header=><label key={header}>{header}<select disabled={busy} value={files[i]?.mapping?.[header]??''} onChange={event=>{const value=event.target.value;setNotice('');setFiles(previous=>previous.map((f,j)=>{if(i!==j)return f;const mapping={...f.mapping};if(value)mapping[header]=value;else delete mapping[header];return {...f,mapping};}));}}><option value="">Keep original name</option>{metricColumns.map(column=><option key={column}>{column}</option>)}</select></label>)}</div>}</details>)}
    <div className="case-actions"><button disabled={busy||disabled||!files.length} onClick={()=>void analyze()}>Analyze selected evidence</button>{busy&&<button onClick={()=>{controller.current?.abort();setBusy(false);setNotice('Parsing cancelled; existing results were kept.');}}>Cancel parsing</button>}<button disabled={busy} onClick={()=>{setFiles([]);setHeaders([]);setError('');setNotice('Selection cleared; existing results were kept.');}}>Clear selection</button></div><p role="alert" className="error">{error}</p><p role="status" className="description">{busy?'Parsing in the background...':notice}</p></section>;
}
