"use client";
import { useEffect, useId, useRef, useState } from 'react';
import { localExplanation, validateExplanation, type Explanation, type ExplanationInput } from '../lib/explanations';
import type { Diagnosis } from '../lib/dataset';
export default function ExplanationAssistant({diagnosis}:{diagnosis:Diagnosis}) {
 const input:ExplanationInput={id:diagnosis.id,title:diagnosis.title,evidence:diagnosis.support.slice(0,8).map((text,i)=>({id:`E${i+1}`,text:text.slice(0,1500)})),conflicts:diagnosis.conflicts.slice(0,8).map(s=>s.slice(0,1000)),missing:diagnosis.missing.slice(0,8).map(s=>s.slice(0,1000)),experiment:diagnosis.experiment.slice(0,2000)};
 // Remount when context changes, so consent and output never apply to stale evidence.
 return <AssistantBody key={JSON.stringify(input)} input={input}/>;
}
function AssistantBody({input}:{input:ExplanationInput}) {
 const [available,setAvailable]=useState(false),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<{mode:string;explanation:Explanation}|null>(null);
 const controller=useRef<AbortController|null>(null);const id=useId();
 useEffect(()=>{const c=new AbortController();fetch('/api/explain',{signal:c.signal}).then(r=>r.ok?r.json():null).then(data=>{if(!c.signal.aborted)setAvailable(data?.aiAvailable===true);}).catch(()=>{});return()=>{c.abort();controller.current?.abort();};},[]);
 async function explain(){if(!consent)return;const c=new AbortController();controller.current=c;setBusy(true);setError('');setResult(null);try{const response=await fetch('/api/explain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'ai',consent:true,hypothesis:input}),signal:c.signal});const data=await response.json();if(!response.ok)throw new Error(data.error??'Explanation unavailable.');if(!c.signal.aborted)setResult({mode:'AI-generated inference',explanation:validateExplanation(data.explanation,input)});}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Explanation unavailable.');}finally{if(!c.signal.aborted)setBusy(false);}}
 return <details className="explanation-assistant"><summary>08 / Evidence-grounded explanation</summary><p className="description">The local explanation runs in your browser. Optional AI sends only the previewed hypothesis and excerpts through this app to OpenAI. It does not send complete files or change your diagnosis ranking.</p><details><summary>Review the exact evidence payload</summary><pre>{JSON.stringify(input,null,2)}</pre></details><div className="case-actions"><button disabled={busy} onClick={()=>{setError('');setResult({mode:'Local rule-based explanation',explanation:localExplanation(input)});}}>Explain locally</button><button disabled={busy||!available||!consent} onClick={()=>void explain()}>Ask AI using these excerpts</button>{busy&&<button onClick={()=>{controller.current?.abort();setBusy(false);setError('Request cancelled. A provider request already sent may still incur usage.');}}>Cancel</button>}</div><label className="experiment-check" htmlFor={`${id}-consent`}><input id={`${id}-consent`} type="checkbox" checked={consent} disabled={busy||!available} onChange={e=>setConsent(e.target.checked)}/>Send the previewed excerpts to OpenAI for this explanation.</label><p className="description">{available?'AI is enabled by the server. Provider data policies apply; responses are requested with storage disabled.':'AI is unavailable or not configured. Local explanations work without an API key.'}</p><p role="alert" className="error">{error}</p>{result&&<section aria-label="Explanation result"><p role="status" className="eyebrow cyan">{result.mode}</p><p>{result.explanation.summary}</p>{result.explanation.claims.map((claim,i)=><p key={i}>{claim.text} <strong>[{claim.evidenceIds.join(', ')}]</strong></p>)}<h4>Limitations</h4><p>{result.explanation.limitations}</p><h4>Next verification</h4><p>{result.explanation.nextStep}</p><h4>Source excerpts</h4><ul>{input.evidence.map(e=><li key={e.id}><strong>{e.id}</strong>: {e.text}</li>)}</ul><p className="description">Evidence references are checked, but references alone do not verify the reasoning. Review AI claims against the excerpts. This explanation is temporary and is not saved with the case.</p></section>}</details>;
}
