import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import ts from 'typescript';
import {localExplanation} from '../app/lib/explanations.ts';
const require=createRequire(import.meta.url);
const source=fs.readFileSync(new URL('../app/api/explain/route.ts',import.meta.url),'utf8');
function load(source){const testModule={exports:{}};const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('module','exports','require',js)(testModule,testModule.exports,name=>{if(name==='server-only')return {};if(name.includes('openai-service'))return service();return require('../app/lib/explanations.ts');});return testModule.exports;}
function service(){return load(fs.readFileSync(new URL('../app/lib/server/openai-service.ts',import.meta.url),'utf8'));}
function route(){return load(source);}
const hypothesis={id:'shift',title:'Possible shift',evidence:[{id:'E1',text:'A reported validation/production gap'}],conflicts:[],missing:['Matched holdout'],experiment:'Compare environments.'};
const request=(payload,origin='http://localhost:3000')=>new Request('http://localhost:3000/api/explain',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(payload)});
function configure(t){const previous={...process.env};process.env.WHYLAB_AI_ENABLED='true';process.env.OPENAI_API_KEY='test-only-key';process.env.OPENAI_MODEL='test-model';const original=globalThis.fetch;t.after(()=>{for(const key of ['WHYLAB_AI_ENABLED','OPENAI_API_KEY','OPENAI_MODEL']){if(previous[key]===undefined)delete process.env[key];else process.env[key]=previous[key];}globalThis.fetch=original;});}
test('local endpoint works without invoking a provider',async t=>{configure(t);globalThis.fetch=()=>{throw new Error('Network must not be used');};const response=await route().POST(request({mode:'local',hypothesis}));assert.equal(response.status,200);assert.equal((await response.json()).mode,'local');assert.equal(response.headers.get('cache-control'),'no-store');});
test('cross-origin and missing-consent requests fail before provider calls',async t=>{configure(t);globalThis.fetch=()=>{throw new Error('Must not call provider');};const api=route();assert.equal((await api.POST(request({mode:'ai',consent:true,hypothesis},'https://other.example'))).status,403);assert.equal((await api.POST(request({mode:'ai',hypothesis}))).status,400);});
test('disabled AI and oversized requests fail clearly',async t=>{configure(t);process.env.WHYLAB_AI_ENABLED='false';const api=route();assert.equal((await api.POST(request({mode:'ai',consent:true,hypothesis}))).status,503);assert.equal((await api.POST(request({padding:'x'.repeat(25000)}))).status,400);});
test('successful AI uses private credentials, structured outputs, and no storage',async t=>{configure(t);globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/responses');const body=JSON.parse(options.body);assert.equal(body.store,false);assert.equal(body.max_output_tokens,1800);assert.equal(body.text.format.type,'json_schema');assert.equal(body.model,'test-model');assert.equal(options.headers.Authorization,'Bearer test-only-key');return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(localExplanation(hypothesis))}]}]});};const response=await route().POST(request({mode:'ai',consent:true,hypothesis}));assert.equal(response.status,200);assert.equal((await response.json()).mode,'ai');});
test('bad citations, refusals, timeouts and provider errors use a safe error',async t=>{configure(t);const invalid={...localExplanation(hypothesis),claims:[{text:'unsupported',evidenceIds:['E9']}]};for(const mode of ['citation','refusal','timeout','error']){globalThis.fetch=async()=>{if(mode==='timeout')throw new Error('secret diagnostic');if(mode==='error')return new Response('secret diagnostic',{status:500});return Response.json({status:'completed',output:[{type:'message',content:mode==='refusal'?[{type:'refusal',refusal:'no'}]:[{type:'output_text',text:JSON.stringify(invalid)}]}]});};const response=await route().POST(request({mode:'ai',consent:true,hypothesis}));assert.equal(response.status,502);assert.ok(!(await response.text()).includes('secret diagnostic'));}});

test('service rejects missing configuration without network or secret diagnostics',async t=>{configure(t);const records=[];t.mock.method(console,'info',(...args)=>records.push(args));globalThis.fetch=()=>{throw new Error('must not fetch');};for(const key of ['OPENAI_MODEL','OPENAI_API_KEY']){const saved=process.env[key];process.env[key]=' ';assert.equal(service().isAIConfigured(),false);await assert.rejects(service().explainWithOpenAI(hypothesis,new AbortController().signal),e=>e.code==='not_configured');process.env[key]=saved;}assert.ok(!JSON.stringify(records).includes('test-only-key'));});
test('safe diagnostics distinguish HTTP, malformed output and refusal without logging bodies',async t=>{configure(t);const records=[];t.mock.method(console,'info',(...args)=>records.push(args));for(const [response,code] of [[new Response('secret-body',{status:429}),'http_error'],[Response.json({status:'incomplete',output:[]}), 'invalid_response'],[Response.json({status:'completed',output:[{type:'message',content:[{type:'refusal',refusal:'secret-body'}]}]}),'refused'],[Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'secret-body'}]}]}),'validation_failed']]){globalThis.fetch=async()=>response;await assert.rejects(service().explainWithOpenAI(hypothesis,new AbortController().signal),e=>e.code===code&&!e.message.includes('secret'));}const logs=JSON.stringify(records);for(const text of ['secret-body','test-only-key','Possible shift'])assert.ok(!logs.includes(text));assert.equal(records[0][1].httpStatus,429);});
test('cancellation and timeout are classified and prevent provider execution',async t=>{configure(t);t.mock.method(console,'info',()=>{});globalThis.fetch=()=>{throw new Error('must not fetch');};const controller=new AbortController();controller.abort();await assert.rejects(service().explainWithOpenAI(hypothesis,controller.signal),e=>e.code==='cancelled');t.mock.method(AbortSignal,'timeout',()=>AbortSignal.abort());await assert.rejects(service().explainWithOpenAI(hypothesis,new AbortController().signal),e=>e.code==='timeout');});
