import test from 'node:test';
import assert from 'node:assert/strict';
import {ingestEvaluationCsv} from '../app/lib/investigation/evaluation-ingestion.ts';
import {runInvestigator, INVESTIGATOR_LIMITS} from '../app/lib/investigation/investigator.ts';
import {buildFinalInvestigation, validateFinalInvestigation} from '../app/lib/investigation/final-diagnosis.ts';
import {serializeInvestigation, parseInvestigation} from '../app/lib/investigation/validation.ts';
const data=(tn,fp,fn,tp)=>ingestEvaluationCsv('y_true,y_pred,y_probability\n'+[[tn,'0,0,.1'],[fp,'0,1,.9'],[fn,'1,0,.1'],[tp,'1,1,.9']].flatMap(([n,r])=>Array(n).fill(r)).join('\n'),'fixture.csv');
async function investigate(d,{stop=false,untested=false}={}){let turn=0;return runInvestigator({objective:'Investigate accuracy',datasets:[d],consent:true,accuracyParadoxGap:10},async history=>{turn++;if(stop&&turn===2)throw new Error('private error');const last=turn>1?JSON.parse(history.at(-1).output):null;let name,args;
if(turn===1){name='compute_classification_metrics';args={datasetId:d.metadata.id,positiveLabel:'1'};}
else if(turn===2){name='propose_hypothesis';args={kind:untested?'other':'accuracy_paradox',statement:untested?'Accuracy is 99.99% because of leakage':'Imbalance',evidenceIds:last.evidence.map(e=>e.id),missingEvidence:['Independent evaluation']};}
else if(turn===3&&!untested){name='run_counterfactual_test';args={datasetId:d.metadata.id,positiveLabel:'1',hypothesisId:last.hypothesis.id,method:'accuracy_paradox',seed:42,criterion:{metric:'accuracy_paradox_gap',operator:'at_least',value:10,unit:'percentage_points'}};}
else{name='finish_investigation';args={reason:'sufficient_evidence',evidenceIds:untested?last.hypothesis.evidence.map(e=>e.evidenceId):last.evidence.map(e=>e.id),missingEvidence:[]};}
return {status:'completed',output:[{type:'function_call',name,call_id:`call_${turn}`,arguments:JSON.stringify(args)}]};},new AbortController().signal);}

test('supported verification produces a canonical final diagnosis with stable provenance',async()=>{const run=await investigate(data(90,0,10,0)),before=structuredClone(run),final=buildFinalInvestigation(run);assert.equal(final.status,'completed');assert.equal(final.diagnosis.status,'completed');assert.equal(final.hypotheses[0].status,'supported');assert.equal(final.diagnosis.primaryHypothesisId,final.hypotheses[0].id);assert.equal(final.diagnosis.confidence.level,'limited');assert.deepEqual(final.repairs,[]);assert.deepEqual(final.comparisons,[]);assert.deepEqual(run,before);assert.deepEqual(parseInvestigation(serializeInvestigation(final)),final);assert.deepEqual(validateFinalInvestigation(final),final);});
test('weakens, rejects and inconclusive verification use consistent statuses',async()=>{for(const [d,status] of [[data(90,0,2,8),'weakened'],[data(90,0,0,10),'rejected'],[data(10,0,10,0),'proposed']]){const final=buildFinalInvestigation(await investigate(d));assert.equal(final.hypotheses[0].status,status);assert.equal(final.diagnosis.status,'inconclusive');assert.equal(final.diagnosis.primaryHypothesisId,null);}});
test('stopped run retains partial evidence and reports failed diagnosis',async()=>{const run=await investigate(data(90,0,10,0),{stop:true}),final=buildFinalInvestigation(run);assert.equal(final.status,'failed');assert.equal(final.diagnosis.status,'failed');assert.equal(final.toolResults.length,1);assert.equal(final.evidence.length,1);assert.ok(!JSON.stringify(final).includes('private error'));});
test('untested proposals cannot promote model-authored numerical claims',async()=>{const run=await investigate(data(90,0,10,0),{untested:true}),final=buildFinalInvestigation(run);assert.ok(run.hypotheses[0].statement.includes('99.99'));assert.ok(!JSON.stringify(final).includes('99.99'));assert.equal(final.hypotheses[0].status,'proposed');assert.equal(final.diagnosis.status,'inconclusive');});
test('unreferenced hypotheses and fabricated completion references are rejected',async()=>{const run=await investigate(data(90,0,10,0));const a=structuredClone(run);a.hypotheses[0].evidence=[];assert.throws(()=>buildFinalInvestigation(a));const b=structuredClone(run);b.completion.evidenceIds=['evidence_fake'];assert.throws(()=>buildFinalInvestigation(b));});
test('tampered outcomes cannot overrule the numerical experiment rule',async()=>{const final=buildFinalInvestigation(await investigate(data(90,0,10,0)));final.experiments[0].outcome='rejects';final.toolResults.find(r=>r.tool==='run_counterfactual_test').output.outcome='rejects';assert.throws(()=>validateFinalInvestigation(final),/numerical rule/);});
test('copied measurement evidence must equal the executed comparison',async()=>{const final=buildFinalInvestigation(await investigate(data(90,0,10,0)));final.evidence.find(e=>e.kind==='measurement').measurements[0].value=.99;assert.throws(()=>validateFinalInvestigation(final),/comparison measurements/);});
test('gap must derive from recorded baseline metrics',async()=>{const final=buildFinalInvestigation(await investigate(data(90,0,10,0)));final.toolResults.find(r=>r.tool==='run_counterfactual_test').output.baseline.find(m=>m.name==='accuracy').value=.95;assert.throws(()=>validateFinalInvestigation(final),/baseline metrics/);});
test('invented numerical summaries, status promotion and confirmation fail validation',async()=>{const source=buildFinalInvestigation(await investigate(data(90,0,10,0)));for(const modify of [v=>v.diagnosis.summary='Accuracy is 99.99%',v=>v.hypotheses[0].status='confirmed',v=>v.hypotheses[0].statement='Accuracy is 99.99%']){const v=structuredClone(source);modify(v);assert.throws(()=>validateFinalInvestigation(v));}});
test('changed criteria and experiment call links are rejected',async()=>{const final=buildFinalInvestigation(await investigate(data(90,0,10,0)));final.experiments[0].criterion.value=20;assert.throws(()=>validateFinalInvestigation(final),/executed call/);});
test('active runs cannot be finalized',async()=>{const run=await investigate(data(90,0,10,0));run.status='running';assert.throws(()=>buildFinalInvestigation(run),/active run/);});
test('empty stopped run is a valid failed investigation',async()=>{const d=data(90,0,10,0),c=new AbortController();c.abort();const run=await runInvestigator({objective:'Investigate',datasets:[d],consent:true,accuracyParadoxGap:10},()=>{throw new Error('must not call');},c.signal,INVESTIGATOR_LIMITS);const final=buildFinalInvestigation(run);assert.equal(final.diagnosis.status,'failed');assert.deepEqual(final.diagnosis.evidenceIds,[]);});

test('conflicting verification preserves both outcomes and leaves the hypothesis unresolved',async()=>{const a=data(90,0,10,0),b=data(90,0,0,10);let turn=0,hypothesisId;const run=await runInvestigator({objective:'Compare verification populations',datasets:[a,b],consent:true,accuracyParadoxGap:10},async history=>{turn++;const last=turn>1?JSON.parse(history.at(-1).output):null;let name,args;if(turn===1){name='compute_classification_metrics';args={datasetId:a.metadata.id,positiveLabel:'1'};}else if(turn===2){name='propose_hypothesis';args={kind:'accuracy_paradox',statement:'Imbalance',evidenceIds:last.evidence.map(e=>e.id),missingEvidence:[]};}else if(turn===3||turn===4){if(turn===3)hypothesisId=last.hypothesis.id;name='run_counterfactual_test';args={datasetId:(turn===3?a:b).metadata.id,positiveLabel:'1',hypothesisId,method:'accuracy_paradox',seed:0,criterion:{metric:'accuracy_paradox_gap',operator:'at_least',value:10,unit:'percentage_points'}};}else{name='finish_investigation';args={reason:'sufficient_evidence',evidenceIds:last.evidence.map(e=>e.id),missingEvidence:[]};}return {status:'completed',output:[{type:'function_call',call_id:`conflict_${turn}`,name,arguments:JSON.stringify(args)}]};},new AbortController().signal);const final=buildFinalInvestigation(run);assert.deepEqual(final.experiments.map(e=>e.outcome),['supports','rejects']);assert.equal(final.hypotheses[0].status,'proposed');assert.equal(final.diagnosis.status,'inconclusive');assert.equal(final.diagnosis.primaryHypothesisId,null);assert.ok(final.hypotheses[0].evidence.some(e=>e.relationship==='rejects'));});
