import test from 'node:test';
import assert from 'node:assert/strict';
import { ingestEvaluationCsv } from '../app/lib/investigation/evaluation-ingestion.ts';
import { runInvestigator, INVESTIGATOR_LIMITS } from '../app/lib/investigation/investigator.ts';
import { executeDiagnostic } from '../app/lib/investigation/tool-registry.ts';
import { investigatorTools } from '../app/lib/investigation/investigator-tools.ts';
import { toolNames } from '../app/lib/investigation/tool-contracts.ts';
const dataset = () => ingestEvaluationCsv('y_true,y_pred,y_probability,feature_x,site\n'+Array.from({length:100},(_,i)=>`${i<90?0:1},0,0.1,${i},${i%2?'A':'B'}`).join('\n'),'fixture.csv');
const signal = () => new AbortController().signal;
const request = d => ({objective:'Investigate misleading accuracy',datasets:[d],consent:true,accuracyParadoxGap:10});
const response = (name,args,id='call_1') => ({status:'completed',output:[{type:'function_call',call_id:id,name,arguments:JSON.stringify(args)}]});
const last = history => JSON.parse(history.at(-1).output);
const scripted = steps => {let index=0;return async history=>{assert.ok(index<steps.length,'unexpected extra provider call');const step=steps[index++];const [name,args]=typeof step==='function'?step(history):step;return response(name,args,`call_${index}`);};};
const finish = history => ['finish_investigation',{reason:'sufficient_evidence',evidenceIds:last(history).evidence.map(e=>e.id),missingEvidence:[]}];
const metrics = d => ['compute_classification_metrics',{datasetId:d.metadata.id,positiveLabel:'1'}];

test('model-selected metrics -> hypothesis -> falsification -> explicit completion retains measured evidence',async()=>{
 const d=dataset(),before=structuredClone(d);
 const run=await runInvestigator(request(d),scripted([metrics(d),h=>['propose_hypothesis',{kind:'accuracy_paradox',statement:'Potential imbalance',evidenceIds:last(h).evidence.map(e=>e.id),missingEvidence:['Controlled comparison']}],h=>['run_counterfactual_test',{datasetId:d.metadata.id,positiveLabel:'1',hypothesisId:last(h).hypothesis.id,method:'accuracy_paradox',seed:42,criterion:{metric:'accuracy_paradox_gap',operator:'at_least',value:10,unit:'percentage_points'}}],finish]),signal());
 assert.equal(run.status,'completed');assert.equal(run.toolResults.length,2);assert.equal(run.experiments[0].outcome,'supports');assert.equal(run.hypotheses[0].status,'proposed');assert.equal(run.experiments[0].hypothesisId,run.hypotheses[0].id);assert.deepEqual(d,before);assert.deepEqual(JSON.parse(JSON.stringify(run)),run);
 for(const id of run.completion.evidenceIds)assert.ok(run.evidence.some(e=>e.id===id));
});
test('all eight allowlisted diagnostics execute and retain canonical outputs',()=>{
 const d=dataset(),other=dataset(),map=new Map([[d.metadata.id,d],[other.metadata.id,other]]),evaluation={datasetId:d.metadata.id,positiveLabel:'1'};
 const inputs={profile_dataset:{datasetId:d.metadata.id,targetColumn:'y_true'},compute_classification_metrics:evaluation,threshold_sweep:{...evaluation,thresholds:[0,.5,1],costs:null},check_calibration:{...evaluation,bins:5,strategy:'equal_width'},scan_feature_leakage:{datasetId:d.metadata.id,targetColumn:'y_true',featureColumns:['feature_x'],predictionTimeColumn:null,outcomeTimeColumn:null,assumptionEvidenceIds:[]},run_drift_tests:{referenceDatasetId:d.metadata.id,comparisonDatasetId:other.metadata.id,columns:['feature_x'],method:'psi',bins:5},slice_evaluation:{...evaluation,columns:['site'],minimumSampleSize:10},run_counterfactual_test:{...evaluation,hypothesisId:'hypothesis_test',method:'accuracy_paradox',seed:42,criterion:{metric:'accuracy_paradox_gap',operator:'at_least',value:10,unit:'percentage_points'}}};
 for(const tool of toolNames){const r=executeDiagnostic({id:'call_test',investigationId:'investigation_test',tool,toolVersion:1,requestedAt:new Date().toISOString(),input:inputs[tool]},map);assert.equal(r.result.status,'completed');assert.equal(r.result.tool,tool);assert.ok(r.evidence.length);assert.equal(r.evidence.at(-1).provenance.resultId,r.result.id);}
 assert.deepEqual(investigatorTools.slice(0,8).map(t=>t.name).sort(),[...toolNames].sort());
});
test('duplicate calls reuse evidence and stop rather than looping forever',async()=>{const d=dataset();let i=0;const run=await runInvestigator(request(d),async()=>response(...metrics(d),`call_${++i}`),signal());assert.equal(run.stopReason,'error_limit');assert.equal(run.toolResults.length,1);assert.equal(run.evidence.length,1);assert.equal(i,4);});
test('threshold candidate order does not bypass deduplication',async()=>{const d=dataset();const base={datasetId:d.metadata.id,positiveLabel:'1',costs:null};const run=await runInvestigator(request(d),scripted([['threshold_sweep',{...base,thresholds:[0,.5,1]}],['threshold_sweep',{...base,thresholds:[1,.5,0]}],h=>{assert.equal(last(h).cached,true);return ['finish_investigation',{reason:'sufficient_evidence',evidenceIds:last(h).data.evidence.map(e=>e.id),missingEvidence:[]}];}]),signal());assert.equal(run.status,'completed');assert.equal(run.toolCalls.length,1);});
test('unsupported tools, unknown dataset IDs and invalid arguments never produce evidence',async()=>{const d=dataset();for(const [name,args] of [['exec',{cmd:'bad'}],['compute_classification_metrics',{datasetId:'dataset_missing',positiveLabel:'1'}],['profile_dataset',{datasetId:d.metadata.id,targetColumn:'y_true',extra:true}]]){let i=0;const run=await runInvestigator(request(d),async()=>response(name,args,`call_${++i}`),signal());assert.equal(run.stopReason,'error_limit');assert.equal(run.evidence.length,0);}});
test('hallucinated evidence cannot ground a proposal or completion',async()=>{const d=dataset();for(const name of ['propose_hypothesis','finish_investigation']){let i=0;const args=name==='propose_hypothesis'?{kind:'other',statement:'Test',evidenceIds:['evidence_fake'],missingEvidence:[]}:{reason:'sufficient_evidence',evidenceIds:['evidence_fake'],missingEvidence:[]};const run=await runInvestigator(request(d),async()=>response(name,args,`call_${++i}`),signal());assert.equal(run.stopReason,'error_limit');assert.equal(run.hypotheses.length,0);assert.equal(run.completion,null);}});
test('malformed output, refusal, incomplete responses and multiple calls fail closed',async()=>{const d=dataset();for(const raw of [null,{status:'incomplete',output:[]},{status:'completed',output:[{type:'message',content:[{type:'refusal'}]}]},{status:'completed',output:[]},{status:'completed',output:[...response(...metrics(d)).output,...response(...metrics(d),'call_2').output]}]){const run=await runInvestigator(request(d),async()=>raw,signal());assert.equal(run.status,'stopped');assert.equal(run.toolResults.length,0);}});
test('duplicate provider call IDs are rejected',async()=>{const d=dataset();const run=await runInvestigator(request(d),async()=>response(...metrics(d),'same'),signal());assert.equal(run.stopReason,'invalid_call');assert.equal(run.toolResults.length,1);});
test('round and tool budgets cannot be bypassed with distinct operations',async()=>{const d=dataset();const steps=[metrics(d),['profile_dataset',{datasetId:d.metadata.id,targetColumn:'y_true'}]];let run=await runInvestigator(request(d),scripted(steps),signal(),{...INVESTIGATOR_LIMITS,rounds:1});assert.equal(run.stopReason,'round_limit');run=await runInvestigator(request(d),scripted(steps),signal(),{...INVESTIGATOR_LIMITS,tools:1});assert.equal(run.stopReason,'tool_limit');assert.equal(run.toolResults.length,1);});
test('expensive calls and unsupported assumptions produce failed results without measured evidence',async()=>{const d=dataset();const run=await runInvestigator(request(d),scripted([['threshold_sweep',{datasetId:d.metadata.id,positiveLabel:'1',thresholds:Array.from({length:52},(_,i)=>i/51),costs:null}]]),signal(),{...INVESTIGATOR_LIMITS,rounds:1});assert.equal(run.toolResults[0].status,'error');assert.equal(run.evidence.length,0);});
test('caller cancellation and deadline stop even an uncooperative provider',async()=>{const d=dataset(),controller=new AbortController();const timer=setTimeout(()=>controller.abort(),10);try{assert.equal((await runInvestigator(request(d),()=>new Promise(()=>{}),controller.signal)).stopReason,'cancelled');}finally{clearTimeout(timer);}const hold=setTimeout(()=>{},100);try{assert.equal((await runInvestigator(request(d),()=>new Promise(()=>{}),signal(),{...INVESTIGATOR_LIMITS,durationMs:10})).stopReason,'deadline');}finally{clearTimeout(hold);}});
test('provider errors preserve already executed evidence and redact errors',async()=>{const d=dataset();let i=0;const run=await runInvestigator(request(d),async()=>{if(i++)throw new Error('secret-provider-body');return response(...metrics(d));},signal());assert.equal(run.stopReason,'provider_error');assert.equal(run.toolResults.length,1);assert.ok(!JSON.stringify(run).includes('secret-provider-body'));});
test('consent, limits, dataset uniqueness and declared criterion are checked before provider execution',async()=>{const d=dataset();const provider=()=>{throw new Error('must not run');};for(const r of [{...request(d),consent:false},{...request(d),datasets:[d,d]},{...request(d),accuracyParadoxGap:0}])await assert.rejects(runInvestigator(r,provider,signal()));await assert.rejects(runInvestigator(request(d),provider,signal(),{...INVESTIGATOR_LIMITS,tools:100}));});
test('transcript and provider response sizes are bounded',async()=>{const d=dataset();assert.equal((await runInvestigator(request(d),()=>{throw new Error('must not call');},signal(),{...INVESTIGATOR_LIMITS,transcriptBytes:10})).stopReason,'transcript_limit');assert.equal((await runInvestigator(request(d),async()=>({padding:'x'.repeat(100)}),signal(),{...INVESTIGATOR_LIMITS,responseBytes:50})).stopReason,'response_limit');});
test('reasoning items are retained when returning measured tool results',async()=>{const d=dataset();let i=0;const run=await runInvestigator(request(d),async h=>{if(i++===0)return {status:'completed',output:[{type:'reasoning',id:'rs_1',encrypted_content:'opaque',summary:[]},...response(...metrics(d)).output]};assert.ok(h.some(x=>x.type==='reasoning'&&x.encrypted_content==='opaque'));return response(...finish(h),'call_finish');},signal());assert.equal(run.status,'completed');});

test('dataset and limit snapshots cannot change while awaiting provider decisions',async()=>{const d=dataset(),options={...INVESTIGATOR_LIMITS,rounds:1};const run=await runInvestigator(request(d),async()=>{d.rows.forEach(row=>row.predicted='1');options.rounds=100;return response(...metrics(d));},signal(),options);assert.equal(run.stopReason,'round_limit');assert.equal(run.toolResults[0].output.metrics.find(m=>m.name==='accuracy').value,.9);});
test('counterfactual rejects fabricated hypotheses and changed caller criteria',async()=>{const d=dataset();const run=await runInvestigator(request(d),scripted([metrics(d),h=>['propose_hypothesis',{kind:'accuracy_paradox',statement:'Imbalance',evidenceIds:last(h).evidence.map(e=>e.id),missingEvidence:[]}],h=>['run_counterfactual_test',{datasetId:d.metadata.id,positiveLabel:'1',hypothesisId:last(h).hypothesis.id,method:'accuracy_paradox',seed:0,criterion:{metric:'accuracy_paradox_gap',operator:'at_least',value:20,unit:'percentage_points'}}]]),signal(),{...INVESTIGATOR_LIMITS,rounds:3});assert.equal(run.experiments.length,0);assert.equal(run.toolCalls.length,1);const args={datasetId:d.metadata.id,positiveLabel:'1',hypothesisId:'hypothesis_invented',method:'accuracy_paradox',seed:0,criterion:{metric:'accuracy_paradox_gap',operator:'at_least',value:10,unit:'percentage_points'}};assert.equal((await runInvestigator(request(d),scripted([['run_counterfactual_test',args]]),signal(),{...INVESTIGATOR_LIMITS,rounds:1})).experiments.length,0);});
test('PSI configuration is retained with its result for reproducibility',async()=>{const a=dataset(),b=dataset();const run=await runInvestigator({...request(a),datasets:[a,b]},scripted([['run_drift_tests',{referenceDatasetId:a.metadata.id,comparisonDatasetId:b.metadata.id,columns:['feature_x'],method:'psi',bins:2}],finish]),signal());assert.equal(run.artifacts[0].resultId,run.toolResults[0].id);assert.deepEqual(run.artifacts[0].details[0].cutPoints,[49.5]);});
