import test from 'node:test';
import assert from 'node:assert/strict';
import { createId, measurementSchema } from '../app/lib/investigation/primitives.ts';
import { diagnosticToolCallSchema, diagnosticToolResultSchema, toolNames } from '../app/lib/investigation/tool-contracts.ts';
import { validateInvestigation, parseInvestigation, serializeInvestigation } from '../app/lib/investigation/validation.ts';
const at='2026-09-13T12:00:00.000Z';
const strength={kind:'evidence_strength',level:'moderate',rationale:'Observed in supplied fixture; cause not established.'};
const metric={name:'accuracy',status:'measured',value:0.75,unit:'ratio',sampleSize:4};
const criterion={metric:'accuracy',operator:'at_least',value:0.7,unit:'ratio'};
const policy={threshold:0.5,positiveLabel:'yes',comparison:'greater_than_or_equal',costs:null};
const make=()=>({schemaVersion:1,id:'investigation_a',objective:'Investigate evaluation failure',status:'draft',createdAt:at,updatedAt:at,sources:[{id:'source_a',kind:'fixture',name:'evaluation.csv',capturedAt:at,contentDigest:null}],datasets:[{id:'dataset_a',sourceId:'source_a',name:'Evaluation',rowCount:4,columns:['y_true','y_pred','y_probability'],role:'evaluation',task:'binary_classification',targetColumn:'y_true',predictionColumn:'y_pred',probabilityColumn:'y_probability',positiveLabel:'yes'}],evidence:[],toolCalls:[],toolResults:[],hypotheses:[],experiments:[],repairs:[],comparisons:[],events:[],diagnosis:null});
const call=(tool,input)=>({id:'call_a',investigationId:'investigation_a',tool,toolVersion:1,requestedAt:at,input});
const inputs={
 profile_dataset:{datasetId:'dataset_a',targetColumn:'y_true'},
 compute_classification_metrics:{datasetId:'dataset_a',positiveLabel:'yes'},
 threshold_sweep:{datasetId:'dataset_a',positiveLabel:'yes',thresholds:[0,0.5,1],costs:null},
 check_calibration:{datasetId:'dataset_a',positiveLabel:'yes',bins:10,strategy:'equal_width'},
 scan_feature_leakage:{datasetId:'dataset_a',targetColumn:'y_true',featureColumns:['feature_x'],predictionTimeColumn:null,outcomeTimeColumn:null,assumptionEvidenceIds:[]},
 slice_evaluation:{datasetId:'dataset_a',positiveLabel:'yes',columns:['site'],minimumSampleSize:10},
 run_drift_tests:{referenceDatasetId:'dataset_a',comparisonDatasetId:'dataset_b',columns:['feature_x'],method:'psi',bins:10},
 run_counterfactual_test:{datasetId:'dataset_a',positiveLabel:'yes',hypothesisId:'hypothesis_a',method:'accuracy_paradox',seed:7,criterion},
};
const confusion={truePositive:1,falsePositive:0,trueNegative:2,falseNegative:1};
const classification={positiveLabel:'yes',negativeLabel:'no',sampleSize:4,confusion,metrics:[metric]};
const outputs={
 profile_dataset:{rowCount:4,columns:[{name:'y_true',role:'target',type:'categorical',missingCount:0,distinctCount:2,minimum:null,maximum:null,mean:null}],classes:[{label:'yes',count:2,prevalence:0.5},{label:'no',count:2,prevalence:0.5}],sliceColumns:[]},
 compute_classification_metrics:classification,
 threshold_sweep:{points:[{threshold:0.5,confusion,metrics:[metric]}],selectedThreshold:0.5},
 check_calibration:{metrics:[metric],bins:[{lower:0,upper:1,sampleSize:4,meanProbability:0.5,observedFrequency:0.5}]},
 scan_feature_leakage:{observations:[{feature:'feature_x',classification:'suspicion',method:'target_copy',description:'Requires availability audit',evidenceIds:[],measurements:[]}]},
 slice_evaluation:{overall:classification,slices:[{column:'site',value:'a',sampleSize:4,metrics:[metric],limitations:['Small slice']}]},
 run_drift_tests:{comparisons:[{feature:'feature_x',method:'psi',referenceSize:4,comparisonSize:4,statistic:{name:'psi',status:'measured',value:0,unit:'unitless',sampleSize:8},limitations:[]}]},
 run_counterfactual_test:{hypothesisId:'hypothesis_a',outcome:'inconclusive',baseline:[metric],comparison:[metric],evidenceIds:[],rationale:'No meaningful difference'},
};
const result=(tool,output)=>({id:'result_a',callId:'call_a',tool,toolVersion:1,completedAt:at,datasetIds:['dataset_a'],evidenceIds:[],limitations:[],status:'completed',output});
function observed(){const v=make();v.toolCalls=[call('compute_classification_metrics',inputs.compute_classification_metrics)];v.toolResults=[{...result('compute_classification_metrics',classification),evidenceIds:['evidence_a']}];v.evidence=[{id:'evidence_a',kind:'measurement',description:'Measured accuracy',measurements:[metric],provenance:{kind:'tool_result',resultId:'result_a'}}];v.hypotheses=[{id:'hypothesis_a',statement:'Accuracy may hide minority errors',status:'supported',confidence:strength,evidence:[{evidenceId:'evidence_a',relationship:'supports',rationale:'Review per-class performance'}],unresolvedQuestions:[]}];return v;}
test('canonical snapshot round trip preserves IDs, numbers and provenance without modifying input',()=>{const v=observed();const original=structuredClone(v);assert.deepEqual(parseInvestigation(serializeInvestigation(v)),v);assert.deepEqual(v,original);assert.notEqual(validateInvestigation(v),v);});
test('generated IDs are typed, unique and retained rather than regenerated on parse',()=>{const a=createId('investigation'),b=createId('investigation');assert.notEqual(a,b);const v=make();v.id=a;assert.equal(parseInvestigation(serializeInvestigation(v)).id,a);});
test('all eight tools accept their own input and output contracts',()=>{assert.equal(toolNames.length,8);for(const name of toolNames){assert.equal(diagnosticToolCallSchema.parse(call(name,inputs[name])).tool,name);assert.equal(diagnosticToolResultSchema.parse(result(name,outputs[name])).status,'completed');}});
test('reject unknown tools, incorrect input shapes, unknown fields and versions',()=>{for(const c of [call('invented',{}),call('threshold_sweep',inputs.profile_dataset),{...call('profile_dataset',inputs.profile_dataset),toolVersion:2},call('profile_dataset',{...inputs.profile_dataset,execute:'arbitrary'})])assert.throws(()=>diagnosticToolCallSchema.parse(c));});
test('reject invalid probabilities, duplicate thresholds, invalid bins and identical drift references',()=>{for(const [name,input] of [['threshold_sweep',{...inputs.threshold_sweep,thresholds:[-0.1]}],['threshold_sweep',{...inputs.threshold_sweep,thresholds:[0.5,0.5]}],['check_calibration',{...inputs.check_calibration,bins:1}],['run_drift_tests',{...inputs.run_drift_tests,bins:null}],['run_drift_tests',{...inputs.run_drift_tests,comparisonDatasetId:'dataset_a'}]])assert.throws(()=>diagnosticToolCallSchema.parse(call(name,input)));});
test('undefined metrics retain reasons; invalid units/rates/counts are rejected',()=>{assert.equal(measurementSchema.parse({name:'recall',status:'undefined',reason:'No positive labels',unit:'ratio',sampleSize:0}).status,'undefined');for(const m of [{...metric,value:1.1},{...metric,value:NaN},{...metric,unit:'count',value:1.5},{...metric,unit:'percent'},{name:'recall',status:'undefined',unit:'ratio',sampleSize:0}])assert.throws(()=>measurementSchema.parse(m));});
test('tool failure states are explicit and cannot also include successful output',()=>{for(const status of ['error','unsupported','insufficient_data']){const r={...result('profile_dataset',outputs.profile_dataset),status,error:{code:'NO_ROWS',message:'Supply evaluation rows',retryable:false}};delete r.output;assert.equal(diagnosticToolResultSchema.parse(r).status,status);assert.throws(()=>diagnosticToolResultSchema.parse({...r,output:outputs.profile_dataset}));}});
test('reject dangling IDs, duplicate entities and mismatched tool/result identity',()=>{for(const change of [v=>v.datasets[0].sourceId='source_missing',v=>v.sources.push({...v.sources[0]}),v=>v.toolCalls[0].investigationId='investigation_other',v=>v.toolResults[0].callId='call_missing',v=>v.toolResults[0].datasetIds=['dataset_missing'],v=>v.evidence[0].provenance.resultId='result_missing']){const v=observed();change(v);assert.throws(()=>validateInvestigation(v));}});
test('source coordinates are bounded and dataset columns must exist',()=>{const v=make();v.evidence=[{id:'evidence_a',kind:'observation',description:'Source excerpt',measurements:[],provenance:{kind:'source',sourceId:'source_a',datasetId:'dataset_a',rows:{first:1,last:4},columns:['y_true']}}];validateInvestigation(v);v.evidence[0].provenance.rows.last=5;assert.throws(()=>validateInvestigation(v));v.evidence=[];v.datasets[0].targetColumn='missing';assert.throws(()=>validateInvestigation(v));});
test('assumptions cannot masquerade as measured tool evidence',()=>{const v=observed();v.evidence[0].kind='assumption';assert.throws(()=>validateInvestigation(v));});
test('confidence and confirmed hypotheses require explicit semantics and verification',()=>{const v=observed();v.hypotheses[0].confidence={value:0.99};assert.throws(()=>validateInvestigation(v));v.hypotheses[0].confidence=strength;v.hypotheses[0].status='confirmed';assert.throws(()=>validateInvestigation(v));});
test('completed investigations require a linked diagnosis',()=>{const v=observed();v.status='completed';assert.throws(()=>validateInvestigation(v));v.diagnosis={id:'diagnosis_a',investigationId:v.id,status:'completed',summary:'Further verification needed',evidenceIds:['evidence_a'],hypothesisIds:['hypothesis_a'],primaryHypothesisId:'hypothesis_a',confidence:strength,experimentIds:[],repairIds:[],comparisonIds:[],unresolvedQuestions:[],limitations:['Not a confirmed cause']};validateInvestigation(v);v.diagnosis.primaryHypothesisId='hypothesis_missing';assert.throws(()=>validateInvestigation(v));});
test('observable events enforce type, time and sequence',()=>{const v=make();v.events=[{id:'event_a',sequence:1,at,kind:'dataset_registered',entityId:'dataset_a',message:'Dataset registered'}];validateInvestigation(v);v.events.push({...v.events[0],id:'event_b'});assert.throws(()=>validateInvestigation(v));v.events.pop();v.events[0].entityId='source_a';assert.throws(()=>validateInvestigation(v));});
test('repair comparisons retain policy, criterion and separate evidence',()=>{const v=observed();v.evidence.push({...v.evidence[0],id:'evidence_b'});v.toolResults[0].evidenceIds.push('evidence_b');v.repairs=[{id:'repair_a',hypothesisId:'hypothesis_a',rationale:'Evaluate threshold',evidenceIds:['evidence_a'],kind:'operating_policy',verification:'evaluation_data',datasetId:'dataset_a',policy,criterion}];v.comparisons=[{id:'comparison_a',repairId:'repair_a',datasetId:'dataset_a',baselinePolicy:{...policy,threshold:0.6},afterPolicy:policy,baselineEvidenceIds:['evidence_a'],afterEvidenceIds:['evidence_b'],criterion,status:'inconclusive',limitations:['Contract fixture only']}];validateInvestigation(v);v.comparisons[0].criterion={...criterion,value:0.2};assert.throws(()=>validateInvestigation(v));v.comparisons[0].criterion=criterion;v.comparisons[0].afterEvidenceIds=['evidence_a'];assert.throws(()=>validateInvestigation(v));});
test('reject non-JSON values, cycles, invalid dates, sparse arrays and oversized imports',()=>{for(const bad of [NaN,Infinity,undefined,1n,new Date(),()=>{}]){const v=make();v.objective=bad;assert.throws(()=>validateInvestigation(v));}const v=make();v.extra=v;assert.throws(()=>validateInvestigation(v));const d=make();d.createdAt='2026-02-30T12:00:00.000Z';assert.throws(()=>validateInvestigation(d));d.createdAt=at;d.sources=Array(1);assert.throws(()=>validateInvestigation(d));assert.throws(()=>parseInvestigation('{bad'));assert.throws(()=>parseInvestigation(' '.repeat(8000001)));});

test('outputs reject numerically inconsistent summaries',()=>{const bad=[['compute_classification_metrics',{...classification,sampleSize:5}],['threshold_sweep',{...outputs.threshold_sweep,selectedThreshold:0.2}],['check_calibration',{metrics:[],bins:[{lower:0.9,upper:0.1,sampleSize:0,meanProbability:null,observedFrequency:null}]}],['profile_dataset',{...outputs.profile_dataset,classes:[{label:'yes',count:2,prevalence:0.2}]}],['run_drift_tests',{comparisons:[{...outputs.run_drift_tests.comparisons[0],method:'ks',statistic:{...metric,value:2,unit:'unitless'}}]}]];for(const [name,output] of bad)assert.throws(()=>diagnosticToolResultSchema.parse(result(name,output)));});
test('tool dataset column references cannot point at absent features',()=>{const v=make();v.toolCalls=[call('slice_evaluation',inputs.slice_evaluation)];assert.throws(()=>validateInvestigation(v));});
test('completed experiments require actual completed calls and evidence',()=>{const v=observed();v.experiments=[{id:'experiment_a',hypothesisId:'hypothesis_a',prediction:'Balanced evaluation exposes errors',method:'accuracy_paradox',seed:7,callIds:['call_a'],criterion,status:'completed',outcome:'supports',evidenceIds:['evidence_a'],limitations:[]}];validateInvestigation(v);v.hypotheses[0].status='confirmed';validateInvestigation(v);v.experiments[0].callIds=[];assert.throws(()=>validateInvestigation(v));});
test('unknown properties and dangerous JSON keys cannot enter the canonical model',()=>{const v=make();v.extra='not part of schema';assert.throws(()=>validateInvestigation(v));delete v.extra;const raw=JSON.stringify(v).replace('"schemaVersion":1','"__proto__":{"polluted":true},"schemaVersion":1');assert.throws(()=>parseInvestigation(raw));assert.equal({}.polluted,undefined);});

test('cost assumptions remain explicitly labeled and resolve to assumption evidence',()=>{const v=make();v.sources.push({id:'source_cost',kind:'user_assumption',name:'Cost policy',capturedAt:at,contentDigest:null});v.evidence=[{id:'evidence_cost',kind:'assumption',description:'False negatives cost 50 units; false positives cost 1',measurements:[],provenance:{kind:'source',sourceId:'source_cost',datasetId:null,rows:null,columns:[]}}];v.toolCalls=[call('threshold_sweep',{...inputs.threshold_sweep,costs:{falseNegativeCost:50,falsePositiveCost:1,assumptionEvidenceId:'evidence_cost'}})];validateInvestigation(v);v.evidence[0].kind='measurement';v.evidence[0].measurements=[metric];assert.throws(()=>validateInvestigation(v));});
