import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import ts from 'typescript';
import {ingestEvaluationCsv} from '../app/lib/investigation/evaluation-ingestion.ts';
function load(url){const testModule={exports:{}};const source=fs.readFileSync(url,'utf8');const localRequire=createRequire(url);const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('module','exports','require',js)(testModule,testModule.exports,name=>name==='server-only'?{}:name.includes('openai-service')?load(new URL('../app/lib/server/openai-service.ts',import.meta.url)):localRequire(name));return testModule.exports;}
const service=()=>load(new URL('../app/lib/server/openai-investigator.ts',import.meta.url));
function configure(t){for(const [key,value] of Object.entries({WHYLAB_AI_ENABLED:'true',OPENAI_API_KEY:'test-only-secret',OPENAI_MODEL:'test-model'})){const previous=process.env[key];process.env[key]=value;t.after(()=>{if(previous===undefined)delete process.env[key];else process.env[key]=previous;});}const fetch=globalThis.fetch;t.after(()=>globalThis.fetch=fetch);t.mock.method(console,'info',()=>{});}
const signal=()=>new AbortController().signal;
const request=()=>({objective:'Inspect accuracy',datasets:[ingestEvaluationCsv('y_true,y_pred,y_probability\n0,0,.1\n1,0,.1','test.csv')],consent:true,accuracyParadoxGap:10});
test('real server wrapper sends strict functions and returns measured results with matching call IDs',async t=>{configure(t);let turns=0;const r=request();globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/responses');assert.equal(options.headers.Authorization,'Bearer test-only-secret');const body=JSON.parse(options.body);assert.equal(body.store,false);assert.equal(body.model,'test-model');assert.equal(body.parallel_tool_calls,false);assert.equal(body.tool_choice,'required');assert.equal(body.max_output_tokens,2000);assert.deepEqual(body.include,['reasoning.encrypted_content']);for(const tool of body.tools){assert.equal(tool.strict,true);assert.equal(tool.parameters.additionalProperties,false);assert.deepEqual(tool.parameters.required,Object.keys(tool.parameters.properties));}if(turns++===0)return Response.json({status:'completed',output:[{type:'function_call',call_id:'provider_1',name:'compute_classification_metrics',arguments:JSON.stringify({datasetId:r.datasets[0].metadata.id,positiveLabel:'1'})}]});const last=body.input.at(-1);assert.equal(last.type,'function_call_output');assert.equal(last.call_id,'provider_1');const result=JSON.parse(last.output);assert.equal(result.result.output.metrics.find(m=>m.name==='accuracy').value,.5);return Response.json({status:'completed',output:[{type:'function_call',call_id:'provider_2',name:'finish_investigation',arguments:JSON.stringify({reason:'insufficient_evidence',evidenceIds:result.evidence.map(e=>e.id),missingEvidence:['More evaluation rows']})}]});};const run=await service().investigateWithOpenAI(r,signal());assert.equal(run.status,'completed');assert.equal(run.finalInvestigation.diagnosis.status,'inconclusive');assert.equal(run.finalInvestigation.id,run.id);assert.equal(turns,2);});
test('missing configuration and missing consent never invoke fetch',async t=>{configure(t);globalThis.fetch=()=>{throw new Error('must not fetch');};await assert.rejects(service().investigateWithOpenAI({...request(),consent:false},signal()),e=>e.code==='consent_required');process.env.OPENAI_MODEL='';await assert.rejects(service().investigateWithOpenAI(request(),signal()),e=>e.code==='not_configured');});
test('provider HTTP errors are sanitized and logs contain no secrets or upstream bodies',async t=>{configure(t);const logs=[];t.mock.method(console,'info',(...args)=>logs.push(args));globalThis.fetch=async()=>new Response('sensitive upstream',{status:401});await assert.rejects(service().requestInvestigatorTurn([],signal()),e=>e.code==='http_error'&&!e.message.includes('sensitive'));assert.equal(logs[0][1].httpStatus,401);for(const secret of ['test-only-secret','sensitive upstream'])assert.ok(!JSON.stringify(logs).includes(secret));});
test('oversized and malformed provider bodies are rejected',async t=>{configure(t);for(const [body,code] of [['x'.repeat(262145),'response_limit'],['invalid json','invalid_response']]){globalThis.fetch=async()=>new Response(body);await assert.rejects(service().requestInvestigatorTurn([],signal()),e=>e.code===code);}});
test('provider cancellation and deadline classify safely before network access',async t=>{configure(t);globalThis.fetch=()=>{throw new Error('must not fetch');};const c=new AbortController();c.abort();await assert.rejects(service().requestInvestigatorTurn([],c.signal),e=>e.code==='cancelled');t.mock.method(AbortSignal,'timeout',()=>AbortSignal.abort());await assert.rejects(service().requestInvestigatorTurn([],signal()),e=>e.code==='timeout');});
