import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {investigateMelanoma} from '../app/lib/investigation/flagship-melanoma.ts';
import {buildReliabilityProfile} from '../app/lib/investigation/reliability-profile.ts';
import {buildIncidentReport,incidentReportMarkdown} from '../app/lib/investigation/incident-report.ts';
const fixture=()=>investigateMelanoma(readFileSync(new URL('../public/fixtures/melanoma-synthetic.csv',import.meta.url),'utf8')).investigation;
const component=(v,id)=>buildReliabilityProfile(v).components.find(c=>c.id===id);
test('six transparent dimensions retain provenance, no score and immutable inputs',()=>{const v=fixture(),before=structuredClone(v),p=buildReliabilityProfile(v);assert.equal(p.aggregateScore,null);assert.equal(p.components.length,6);assert.deepEqual(v,before);for(const c of p.components)for(const r of c.readings){assert.ok(v.toolResults.some(t=>t.id===r.resultId));assert.ok(v.toolCalls.some(t=>t.id===r.callId));assert.ok(r.datasetIds.every(id=>v.datasets.some(d=>d.id===id)));}});
test('baseline and after remain separate and multi-point candidate sweeps are excluded',()=>{const v=fixture(),c=component(v,'minority');assert.ok(c.readings.some(r=>r.scope.includes('Baseline')));assert.ok(c.readings.some(r=>r.scope.includes('After')));assert.ok(!c.readings.some(r=>r.resultId==='result_sweep'));const cost=component(v,'cost');assert.equal(cost.checks[0].status,'passed');assert.deepEqual(cost.checks[0].baselineEvidenceIds,v.comparisons[0].baselineEvidenceIds);});
test('missing diagnostics remain not assessed, never safe or reliable',()=>{const p=buildReliabilityProfile(fixture());for(const id of ['calibration','drift','leakage'])assert.equal(p.components.find(c=>c.id===id).availability,'Not assessed');});
function add(v,tool,input,output){const call={id:'call_extra',investigationId:v.id,tool,toolVersion:1,requestedAt:v.updatedAt,input};v.toolCalls.push(call);v.toolResults.push({id:'result_extra',callId:call.id,tool,toolVersion:1,completedAt:v.updatedAt,datasetIds:[v.datasets[0].id],evidenceIds:[],limitations:['Test scope limitation'],status:'completed',output});}
test('undefined calibration metrics are retained without treating them as measured',()=>{const v=fixture();add(v,'check_calibration',{datasetId:v.datasets[0].id,positiveLabel:'1',bins:2,strategy:'equal_width'},{metrics:[{name:'brier_score',status:'undefined',reason:'Unavailable test value',unit:'loss',sampleSize:100}],bins:[{lower:0,upper:1,sampleSize:100,meanProbability:.2,observedFrequency:.1}]});const c=component(v,'calibration');assert.equal(c.availability,'No defined measurements');assert.equal(c.readings[0].measurement.status,'undefined');assert.equal(c.readings[0].resultId,'result_extra');});
test('leakage findings retain suspicion classification and empty scans are not safety claims',()=>{const v=fixture();add(v,'scan_feature_leakage',{datasetId:v.datasets[0].id,targetColumn:'y_true',featureColumns:['y_probability'],predictionTimeColumn:null,outcomeTimeColumn:null,assumptionEvidenceIds:[]},{observations:[{feature:'y_probability',classification:'suspicion',method:'test',description:'Requires provenance review',evidenceIds:[],measurements:[]}]});const c=component(v,'leakage');assert.equal(c.findings[0].classification,'suspicion');assert.equal(c.availability,'No defined measurements');});
test('report embeds deterministic profile and invalid canonical references fail closed',()=>{const v=fixture(),r=buildIncidentReport(v);assert.deepEqual(r.reliabilityProfile,buildReliabilityProfile(v));assert.match(incidentReportMarkdown(r),/## Reliability profile/);v.evidence[1].provenance.resultId='result_unknown';assert.throws(()=>buildReliabilityProfile(v));});
