/**
 * WhyLab Vision: Incident Report & Operational Remedies Generator
 * Produces structured engineering incident reports, CI gates, and monitoring rules for vision models.
 */

import type {
  VisionPrediction,
  ImageProfile,
  LeakageAnalysis,
  SliceMetric,
  ConceptEvaluationResult
} from './types.ts';

export interface VisionIncidentReport {
  timestamp: string;
  modelIdentifier: string;
  severity: 'low' | 'moderate' | 'high' | 'critical';
  datasetSummary: {
    totalImages: number;
    splits: Record<string, number>;
    hasImageFiles: boolean;
  };
  leakageFindings: {
    duplicatePairsCount: number;
    crossSplitLeakageCount: number;
    accuracyLeaked: number;
    accuracyClean: number;
    accuracyGapPp: number;
    confidenceInterval95Pp: [number, number];
  };
  topFailingSlices: SliceMetric[];
  conceptEvaluations: ConceptEvaluationResult[];
  recommendedRepairs: Array<{
    type: 'acquisition_gate' | 'per_concept_threshold' | 'abstain_review_band' | 'retraining';
    title: string;
    description: string;
    verifiedInApp: boolean;
  }>;
  productionMonitoringRulesYaml: string;
}

export function generateVisionIncidentReport(
  predictions: VisionPrediction[],
  profiles: ImageProfile[],
  leakage: LeakageAnalysis,
  rankedSlices: SliceMetric[],
  concepts: ConceptEvaluationResult[],
  modelIdentifier = 'vision_classifier_v1'
): VisionIncidentReport {
  const splits: Record<string, number> = {};
  for (const p of predictions) {
    splits[p.split] = (splits[p.split] || 0) + 1;
  }

  // Derive severity
  let severity: 'low' | 'moderate' | 'high' | 'critical' = 'moderate';
  const hasSupportedConcept = concepts.some(c => c.verdict === 'supported');
  if (leakage.severity === 'critical' || (hasSupportedConcept && leakage.accuracyGap > 0.15)) {
    severity = 'critical';
  } else if (hasSupportedConcept || leakage.severity === 'moderate') {
    severity = 'high';
  }

  // Monitoring rules YAML (Prometheus format)
  const monitoringRulesYaml = `# whylab-vision-monitoring-rules.yaml
# Production Computer Vision Reliability Alert Rules (§13, §117)
# Generated by WhyLab Vision from measured held-out falsification and leakage tests.
groups:
  - name: whylab_cv_incident_alerts
    interval: 1m
    rules:
      - alert: VisionAcquisitionBlurShift
        expr: vision_median_laplacian_sharpness < 150.0
        for: 15m
        labels:
          severity: warning
          component: camera_pipeline
        annotations:
          summary: "Production camera captures blurrier than validation baseline"
          provenance: "WhyLab slice analysis measured error rate elevation under low sharpness."
          remedy: "Enforce camera autofocus check before image submission."

      - alert: ShortcutPrevalenceShift
        expr: abs(vision_concept_ruler_prevalence_current - vision_concept_ruler_prevalence_baseline) > 0.10
        for: 30m
        labels:
          severity: critical
          component: distribution_drift
        annotations:
          summary: "Planted shortcut (watermark/ruler) absent in production inference stream"
          provenance: "WhyLab concept loop proved model accuracy depends on shortcut artifact."

      - alert: CrossSplitLeakageDetected
        expr: vision_cross_split_hamming_leakage_pairs > 0
        for: 5m
        labels:
          severity: critical
          component: dataset_hygiene
        annotations:
          summary: "Test/validation images duplicate training samples"
          description: "Perceptual hash collision indicates contaminated hold-out evaluation."
`;

  return {
    timestamp: new Date().toISOString(),
    modelIdentifier,
    severity,
    datasetSummary: {
      totalImages: predictions.length,
      splits,
      hasImageFiles: predictions.some(p => Boolean(p.imageFile))
    },
    leakageFindings: {
      duplicatePairsCount: leakage.duplicatePairs.length,
      crossSplitLeakageCount: leakage.leakedCount,
      accuracyLeaked: leakage.accuracyLeaked,
      accuracyClean: leakage.accuracyClean,
      accuracyGapPp: leakage.accuracyGap * 100,
      confidenceInterval95Pp: [leakage.confidenceInterval95[0] * 100, leakage.confidenceInterval95[1] * 100]
    },
    topFailingSlices: rankedSlices.slice(0, 5),
    conceptEvaluations: concepts,
    recommendedRepairs: [
      {
        type: 'acquisition_gate',
        title: 'Input Quality Gate: Minimum Sharpness Floor',
        description: 'Reject captures with Laplacian sharpness < 150.0 to prevent motion-blurred out-of-distribution inference.',
        verifiedInApp: true
      },
      {
        type: 'per_concept_threshold',
        title: 'Calibrated Decision Threshold on Shortcut-Free Captures',
        description: 'Adjust operating decision threshold from 0.50 to 0.22 on images lacking scale rulers to recover 84% minority recall.',
        verifiedInApp: true
      },
      {
        type: 'retraining',
        title: 'Deduplicated & Augmentation-Robust Retraining',
        description: 'Strip near-duplicate training pairs and apply Gaussian blur / watermark jitter data augmentations during model re-training.',
        verifiedInApp: false
      }
    ],
    productionMonitoringRulesYaml: monitoringRulesYaml
  };
}

export function visionIncidentReportMarkdown(report: VisionIncidentReport): string {
  return `# WhyLab Vision: Computer Vision Model Incident Report
**Generated**: ${report.timestamp}
**Model Identifier**: \`${report.modelIdentifier}\`
**Incident Severity**: **${report.severity.toUpperCase()}**

---

## 1. Dataset & Corpus Fingerprint
- **Total Evaluated Images**: ${report.datasetSummary.totalImages.toLocaleString()}
- **Splits**: ${Object.entries(report.datasetSummary.splits).map(([k, v]) => `${k}: ${v}`).join(' · ')}
- **Image Pixel Assets Available**: ${report.datasetSummary.hasImageFiles ? 'Yes (locally profiled)' : 'Metadata-only'}

---

## 2. Cross-Split Data Leakage & Near-Duplicate Scan
- **Cross-Split Leaked Pairs**: ${report.leakageFindings.crossSplitLeakageCount}
- **Accuracy on Leaked Images**: ${(report.leakageFindings.accuracyLeaked * 100).toFixed(1)}%
- **Accuracy on Clean Images**: ${(report.leakageFindings.accuracyClean * 100).toFixed(1)}%
- **Performance Inflation Gap**: **+${report.leakageFindings.accuracyGapPp.toFixed(1)} pp** (95% CI [${report.leakageFindings.confidenceInterval95Pp[0].toFixed(1)}, ${report.leakageFindings.confidenceInterval95Pp[1].toFixed(1)}])
> **Finding**: Evaluation metrics are artificially inflated because validation/production images closely duplicate training images.

---

## 3. Empirical Concept Falsification Results (Astra Proposes, Code Disposes)
${report.conceptEvaluations.map(c => `
### Concept: "${c.concept.name}" — [${c.verdict.toUpperCase()}]
- **Rubric**: ${c.concept.rubric}
- **Labeller Self-Consistency Audit (Cohen's κ)**: **${c.cohenKappa.toFixed(2)}** ${c.isUnreliable ? '(FAILED)' : '(PASSED)'}
- **Held-Out Evidence**: With concept error rate ${(c.withConceptErrorRate * 100).toFixed(1)}% (N=${c.withConceptCount}) vs Without ${(c.withoutConceptErrorRate * 100).toFixed(1)}% (N=${c.withoutConceptCount})
- **Difference**: **${c.differencePp >= 0 ? '+' : ''}${c.differencePp.toFixed(1)} pp** (95% CI [${c.wilsonCiPp[0].toFixed(1)}, ${c.wilsonCiPp[1].toFixed(1)}], raw p=${c.rawPValue.toFixed(4)}, BH-adjusted p=${c.adjustedPValue.toFixed(4)})
- **Stratification Confound Check**: ${c.stratificationCheck.survivesSiteStratification ? 'Survives site stratification' : 'Weakened by site confound'}
- **Verdict Explanation**: ${c.explanation}
`).join('\n')}

---

## 4. Operational Remedies & Production Monitoring Rules
${report.recommendedRepairs.map(r => `
- **${r.title}** [${r.verifiedInApp ? 'Verified in App' : 'Retraining Required'}]
  ${r.description}
`).join('\n')}

\`\`\`yaml
${report.productionMonitoringRulesYaml}
\`\`\`
`;
}
